### ISSUE TITLE
How to get simulation data

### ISSUE THREAD

**Issue by leiwang1023** [akmaier/CONRAD#127]
dear, 
First, when I use the "Create Numerical Phantom", ImageJ shows the images. This is phantom or projection data? If it is projection data, how can I get the Original phantom?
Second, if I have an .raw phantom, how can I use CONRAD to get 360° projection data?
Looking forward to your reply and thanks very much.

**Comment by tmgeimer** [comment]
Dear Lei Wang,

thank you for using CONRAD.
The type of phantom is determined by the selection of either the "Metric Volume Phantom" or the "OpenCL Projection Phantom".
You can further select the type of phantom you want to create (e.g. Water cylinder, Shepp-Logan).

If I understand correctly, your goal is to forward project a phantom of your own.
As CONRAD wraps ImageJ, you can use its IO functions to import the *.raw data.
Afterwards define a trajectory for your desired 360° scan and use the OpenCL Forward Projector.

I highly suggest having a look at the rather extensive (yet, not complete) documentation in [1].
Please make sure to navigate the site (left menu) to find worked examples for
1) defining a trajectory
2) forward projection
3) create 3D phantoms
4) reconstruct data

I hope this will help you in taking the first steps. Once you have slightly more concrete questions, feel free to contact us again.

As a side note, there is a CONRAD support mailing list for user questions [2]. Github issues should be reserved to actual problems / bugs within the code. We will update the project page accordingly to refer to the mailing list.

Hope this helps,
Tobias

[1] https://www5.cs.fau.de/conrad/tutorials/user-guide/
[2] project-conrad@lists.fau.de
